[package]
name = "hello-composition-rs"
version = "0.1.0"
authors = ["Joshua Ols <joshua.d.ols@gmail.com>"]
edition = "2018"

[dependencies]
windows = "0.17.2"
# windows = { git = "https://github.com/microsoft/windows-rs.git" }
bindings = { path = "bindings" }
winit = "0.24.0"
raw-window-handle = "0.3.3"
rand = "0.8.3"
