[package]
name = "hello-composition-rs"
version = "0.1.0"
authors = ["Joshua Ols <joshua.d.ols@gmail.com>"]
rust-version = "1.56"
edition = "2021"

[dependencies]
winit = "0.25.0"
raw-window-handle = "0.3.3"
rand = "0.8.4"

[dependencies.windows]
# git = "https://github.com/microsoft/windows-rs"
version = "0.27.0"
features = [
    "alloc",
    "Foundation_Numerics",
    "System",
    "UI_Composition_Desktop",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_WinRT_Composition",
]
