[package]
name = "hello-composition-rs"
version = "0.1.0"
authors = ["Joshua Ols <joshua.d.ols@gmail.com>"]
edition = "2018"

[dependencies]
windows = { git = "https://github.com/microsoft/windows-rs" }
bindings = { path = "bindings" }
winit = "0.22.0"
raw-window-handle = "0.3.3"
rand = "0.7.3"
