[package]
name = "hello-composition-rs"
version = "0.1.0"
authors = ["Joshua Ols <joshua.d.ols@gmail.com>"]
edition = "2021"

[dependencies]
winit = "0.24.0"
raw-window-handle = "0.3.3"
rand = "0.8.3"

[dependencies.windows]
git = "https://github.com/microsoft/windows-rs"
features = [
    "Foundation_Collections",
    "Foundation_Numerics",
    "Graphics",
    "System",
    "UI_Composition_Desktop",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_WinRT",
    "Win32_UI_WindowsAndMessaging",
]
